##############################################################################
# MAIN CONFIG FILE (for running simulations)
##############################################################################

defaults:
  - game: basic
  - simulation: basic
  - _self_ # stuff below can override stuff above  

seed: 42