##############################################################################
# MAIN CONFIG FILE
##############################################################################

defaults:
  - learning:
    - data
    - hyperparameters
  - quantifier:
    - every
  - _self_ # stuff below can override stuff above  

seed: 42
verbose: True

##############################################################################
# Paths of files used for consuming and producing data
##############################################################################
filepaths: 

  ############################################################################
  # Data to read in
  ############################################################################

  bitstrings_dir: data/bitstrings

  quantifier_data_dir: data/quantifier_data

  ############################################################################
  # Hydra automatic folder naming
  ############################################################################

  # holds curve points
  curve_subdir: seed=${seed}

  # for plots etc. that summarize experiment sweeps
  experiment_subdir: 

  # where the current working directory will be when hydra is running
  leaf_subdir: ${filepaths.experiment_subdir}

  # hydra run root directory
  hydra_run_root: outputs

  # hydra multirun root directory
  hydra_sweep_root: multirun

##############################################################################
# Hydra run and sweep configs
##############################################################################
hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}