##############################################################################
# MAIN CONFIG FILE
##############################################################################

defaults:
  - learning:
    - data
    - hyperparameters
  - quantifier:
    - every
  - _self_ # stuff below can override stuff above  

seed: 42
verbose: True

##############################################################################
# Paths of files used for consuming and producing data
##############################################################################
filepaths: 

  ############################################################################
  # Data to read in
  ############################################################################

  bitstrings_dir: data/bitstrings

  quantifier_data_dir: data/quantifier_data

  ############################################################################
  # Outputs
  ############################################################################

  losses_fn: losses.csv

  model_fn: model.pt

  ############################################################################
  # Hydra automatic folder naming
  ############################################################################

  # holds curve points
  curve_subdir: seed=${seed}

  # for plots etc. that summarize experiment sweeps
  experiment_subdir: quantifier=${quantifier.name}/num_states=${learning.num_states}/epochs=${learning.epochs}/batch_size=${learning.batch_size}/lr=${learning.learning_rate}

  # where the current working directory will be when hydra is running
  leaf_subdir: ${filepaths.experiment_subdir}

  # hydra run root directory
  hydra_run_root: outputs

  # hydra multirun root directory
  hydra_sweep_root: multirun

##############################################################################
# Hydra run and sweep configs
##############################################################################
hydra:
  run:
    dir: ${filepaths.hydra_run_root}/${filepaths.leaf_subdir}
  job:
    chdir: True
    config:
      override_dirname:
        exclude_keys:
          - filepaths.leaf_subdir
          - quantifier.name
          - learning.num_states
          - learning.epochs
          - learning.batch_size
          - learning.learning_rate
          - seed

  sweep:
    dir: ${filepaths.hydra_sweep_root}
    subdir: ${filepaths.leaf_subdir}